<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Web Analytics Test Suite" duration-ms="8614" started-at="2016-09-19T10:27:08Z" finished-at="2016-09-19T10:27:17Z">
    <groups>
    </groups>
    <test name="WebAnalytics" duration-ms="8614" started-at="2016-09-19T10:27:08Z" finished-at="2016-09-19T10:27:17Z">
      <class name="web.analytics.test.TestNG">
        <test-method status="PASS" signature="setUp()[pri:0, instance:web.analytics.test.TestNG@3e92efc3]" name="setUp" is-config="true" duration-ms="701" started-at="2016-09-19T15:57:08Z" finished-at="2016-09-19T15:57:08Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="SKIP" signature="executeTestCases(web.analytics.excel.TestCase)[pri:0, instance:web.analytics.test.TestNG@3e92efc3]" name="executeTestCases" duration-ms="0" started-at="2016-09-19T15:57:17Z" data-provider="TestCases" finished-at="2016-09-19T15:57:17Z">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[java.lang.ArrayStoreException: [Ljava.lang.Object;]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: java.lang.ArrayStoreException: [Ljava.lang.Object;
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:163)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:430)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1274)
	at org.testng.internal.Invoker.createParameters(Invoker.java:989)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1079)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
Caused by: java.lang.ArrayStoreException: [Ljava.lang.Object;
	at web.analytics.test.TestNG.getTestCases(TestNG.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:137)
	... 20 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- executeTestCases -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:web.analytics.test.TestNG@3e92efc3]" name="tearDown" is-config="true" duration-ms="0" started-at="2016-09-19T15:57:17Z" finished-at="2016-09-19T15:57:17Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- web.analytics.test.TestNG -->
    </test> <!-- WebAnalytics -->
  </suite> <!-- Web Analytics Test Suite -->
</testng-results>
